name: Obfuscate & compile

# Help: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

on: [push, pull_request]

jobs:
  obfuscate:
    # Run pytest tests on pickle files (pre-generated SC2 API observations)
    name: Obfuscate and compile
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # Python 3.6 fails due to: https://www.python.org/dev/peps/pep-0563/
        # If all type annotations were removed, this library should run in py3.6 and perhaps even 3.5
        os: [windows-latest]
#        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v1
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          mkdir tempFolder
          mkdir mybot_obfuscated
          mkdir mybot_compiled

      - name: Show scipy/.libs folder contents
        run: |
          echo "Showing contents of scipy/.libs folder
          ls C:\hostedtoolcache\windows\Python\3.7.6\x64\Lib\site-packages\scipy\.libs

      # Create config
      - name: Run regex_output_config.py
        run: |
          python regex_output_config.py

      - name: Move bot to tempFolder
        run: |
          move mybot/* tempFolder/

      - name: Obfuscate bot
        run: |
          python opy.py tempFolder mybot_obfuscated tempFolder/opy_config.txt

      - name: Compile using Pyinstaller
        run: |
          python pyinstaller-script.py
          ls mybot_compiled

      - name: Move sc2/ folder to obfuscated folder
        run: |
          move sc2 mybot_obfuscated/
          ls mybot_obfuscated

      - name: Upload obfuscated files
        uses: actions/upload-artifact@v1
        with:
          name: Bot_obfuscated_${{ matrix.python-version }}
          path: mybot_obfuscated

      - name: Upload compiled run.exe file
        uses: actions/upload-artifact@v1
        with:
          name: Bot_compiled_${{ matrix.python-version }}
          path: mybot_compiled

